### ISSUE TITLE
Database Connection String should not be public

### ISSUE THREAD

**Issue by shaswatsaxena** [aryaminus/tomodachi#10]
https://github.com/aryaminus/tomodachi/blob/85f31107309474a0db26cbc44a083ebf552c5d15/app.js#L30

Secrets like db connection strings should be stored in environment variables.
[dotenv](https://www.npmjs.com/package/dotenv)
[config](https://www.npmjs.com/package/config)

**Comment by aryaminus** [comment]
Fixed by usage of heroku config DATABASE_URL
https://github.com/aryaminus/tomodachi/blob/1e68067e04dc9a95d541a17831a579cc37bf6fd9/app.js#L29

defined when pushing local dB to heroku-postgresql .
